[package]
name = "q2309"
version = "0.1.0"
authors = ["sneakstarberry <gihong2012@likelion.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
